name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test-auth:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Subir Auth Service e Banco
        run: docker compose -f infra/docker-compose.yml up -d --build auth-service db

      - name: Aguardar serviços iniciarem
        run: sleep 10

      - name: Executar testes do Auth Service
        run: docker compose -f infra/docker-compose.yml exec -T auth-service pytest

  test-academic:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Subir Academic, Auth e Banco
        run: docker compose -f infra/docker-compose.yml up -d --build academic-service auth-service db

      - name: Aguardar serviços iniciarem
        run: sleep 10

      - name: Executar testes do Academic Service
        run: docker compose -f infra/docker-compose.yml exec -T academic-service pytest

  test-frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies and Lint
        run: |
          cd frontend
          echo "Simulando build e lint do Frontend..."